import type { LandingContent } from './content';

export const LANDING_EN: LandingContent = {
  nav: {
    label: 'Page sections',
    how: 'How it works',
    architecture: 'Architecture',
    tech: 'Technology',
    faq: 'FAQ',
    tryDemo: 'Try the demo',
    home: 'BekenAI home',
  },
  hero: {
    title: 'Every answer has a {em} behind it.',
    titleEm: 'source',
    lead: 'BekenAI searches legislation, Yargıtay (Court of Cassation) decisions and doctrine together. It checks every claim it writes against the passage it rests on, and openly marks what is not supported.',
    languageNote: 'BekenAI works in Turkish: questions, sources and answers are in Turkish. The examples below are real Turkish output.',
    explore: 'Explore the architecture',
    facts: ['Hybrid search', 'Claim-by-claim verification', 'Versioned source record'],
  },
  heroAnimation: {
    label: 'Animation of BekenAI answering a question from its sources and verifying the claims one by one',
    steps: ['Search', 'Writing', 'Verification'],
    searching: 'Searching the sources',
    writing: 'Writing the answer',
    verifying: 'Verifying the claims',
    verified: 'Verified',
    reranked: '25 candidate passages → reranked → 3 sources chosen',
    summary: '3 claims verified',
    supported: '✓ Supported',
    unsupported: '✕ Not supported',
  },
  techLabel: 'TECHNOLOGY',
  tech: [
    ['Next.js', 'React interface · Vercel'],
    ['Tailwind CSS', 'Styling'],
    ['FastAPI', 'API and worker'],
    ['PostgreSQL', 'Versioned legal schema'],
    ['Supabase', 'Auth, data, storage'],
    ['Qdrant', 'Vector search'],
    ['BM25', 'Keyword search with Turkish stemming'],
    ['BGE-M3', 'Multilingual embedding model'],
    ['BGE Reranker v2', 'int8 ONNX reranking'],
    ['Gemini', 'Planning, writing, verification'],
    ['Tavily', 'Optional web search'],
    ['Oracle Cloud', 'Search and model server'],
  ],
  how: {
    label: 'HOW IT WORKS',
    titleLine: 'From search to verification,',
    titleRest: 'every step in view.',
    lead: 'How an answer is produced is never hidden. You see which sources were found, which claim rests on which source, and what was left out.',
    search: {
      title: 'Hybrid search',
      body: 'Keyword and meaning-based search run together. The best 25 candidate passages are rescored by a separate model.',
      results: [
        ['Labour Law · Article 17', 'BM25 · meaning'],
        ['Yargıtay 9th Civil Chamber decision', 'meaning'],
        ['Labour law course note · Termination with notice', 'BM25'],
      ],
      flow: 'BM25 + BGE-M3 → RRF → reranking',
    },
    write: {
      title: 'Writing tied to sources',
      body: 'The answer is written only from the sources found. Each legal claim is its own sentence, linked by number to the source it rests on.',
      source: 'Labour Law No. 4857',
      article: 'Article 17 · Termination with notice',
    },
    verify: {
      title: 'Claim-by-claim verification',
      body: 'Every claim–passage pair is checked by a separate model. An unsupported citation is removed, and a sentence left without support is marked “unverified”. If there is no relevant source at all, BekenAI does not guess.',
      supported: '✓ Supports',
      partial: '◐ Partly',
      unverified: '✕ Unverified',
    },
    passage: {
      title: 'One click to the passage',
      body: 'Click a citation and the side panel opens the whole passage, its citation, the article’s amendment history and the reason it was verified.',
      kind: 'Primary · Legislation',
      source: 'Labour Law No. 4857',
      article: 'Article 17',
      supports: '✓ Supports claims 1 and 2',
    },
  },
  architecture: {
    label: 'ARCHITECTURE',
    title: 'What happens behind the scenes?',
    lead: 'In short: BekenAI is a {rag} system. The model does not make the answer up from memory; it first finds the relevant legal sources, then writes only from them. BekenAI adds one more step: it checks every claim it wrote against its source again.',
    metrics: [
      ['7', 'step pipeline, from gathering sources to verifying claims'],
      ['25', 'candidate passages reranked for every question'],
      ['99%', 'of test questions find the expected article in the top 25 (72 questions)'],
      ['450+', 'automated tests, run in CI on every change'],
    ],
    ragTitle: 'What is RAG, and what does BekenAI do differently?',
    approaches: [
      {
        title: 'A language model alone',
        flow: ['Question', 'Model', 'Answer'],
        body: 'It answers from what it learned in training. It cites no source, and can write something false with the same confidence. This is called hallucination.',
        verdict: 'No source · high risk of hallucination',
        tone: 'err',
      },
      {
        title: 'Classic RAG',
        flow: ['Question', 'Search', 'Sources', 'Model', 'Answer'],
        body: 'It first finds the relevant documents, writes the answer from them and cites them. But it does not check separately whether each sentence is really in the source.',
        verdict: 'Sources cited · sentences not checked',
        tone: 'neutral',
      },
    ],
    oursTitle: 'RAG + claim verification',
    oursBody:
      'Two layers of checks on top of classic RAG: it confirms that the citations written really exist, and it has a separate model compare every claim with the passage it rests on. A question becomes an answer in ten steps.',
    phases: { search: 'search', select: 'selection', write: 'writing', verify: 'verification' },
    ourSteps: [
      { title: 'Query planning', phase: 'search', body: 'The question, together with the earlier messages of the chat, becomes a self-contained search query; up to 3 statute articles that govern the question are named as well.' },
      { title: 'Keyword search', phase: 'search', body: 'BM25 matches words by their first 5 letters, so the Turkish “savunmam” and “savunmasını” are found from the same stem.' },
      { title: 'Meaning search', phase: 'search', body: 'BGE-M3 vectors also catch the same question asked in different words.' },
      { title: 'RRF fusion', phase: 'search', body: 'The two rankings are merged into one list by the positions of the passages.' },
      { title: 'Reranking', phase: 'select', body: 'The best 25 candidates and the articles named in planning are read together with the question and scored again.' },
      { title: 'Context selection', phase: 'select', body: 'Passages are chosen within a token budget: your files first, then legislation and case law, with doctrine in the remaining space. Statute passages carry their official amendment notes.' },
      { title: 'Structured writing', phase: 'write', body: 'The model writes each claim with the ids of the sources it rests on, following a JSON schema; if the model fails, a fallback model takes over.' },
      { title: 'Citation integrity', phase: 'write', body: 'Source ids a sentence may not cite, ones that do not exist or come from the wrong channel, are removed.' },
      { title: 'Claim verification', phase: 'verify', body: 'Every claim–passage pair is labelled “supports”, “partly” or “does not support” by a separate model.' },
      { title: 'Marking and saving', phase: 'verify', body: 'Unsupported citations are removed, and a sentence left without support is marked “unverified”. The answer is saved with its citations and source versions.' },
    ],
    oursVerdict: 'Sources cited · every claim checked · doctrine goes through the same steps in its own channel',
    pipelineTitle: 'From source to answer: how the system works',
    pipelineNote: 'The first three steps run once, as sources are added; the last four run for every question',
    preparation: 'PREPARATION · ONCE, AS SOURCES ARE ADDED',
    everyQuestion: 'FOR EVERY QUESTION',
    technical: 'TECHNICAL',
    pipeline: [
      {
        phase: 'preparation',
        title: 'Gathers the sources',
        en: 'Ingestion',
        plain: 'Laws, Yargıtay decisions and doctrine are loaded into the system. Every update is kept as a separate version, so it is never lost which source an older answer relied on.',
        tech: 'Manifest-based import, duplicate checks by content hash, and an immutable store of the raw documents. Metadata lives in a versioned PostgreSQL schema.',
        tags: ['Python', 'Supabase Storage', 'PostgreSQL'],
      },
      {
        phase: 'preparation',
        title: 'Splits the text into chunks',
        en: 'Chunking',
        plain: 'Documents are split into small chunks that keep their article, paragraph and item structure. An answer then points to the exact passage, not to the whole document.',
        tech: 'A parser that understands legal structure; each chunk carries its citation, article path and page. Changes to an article are tracked as separate versions.',
        tags: ['Structure-aware parser', 'Article versions'],
      },
      {
        phase: 'preparation',
        title: 'Indexes them',
        en: 'Embedding & indexing',
        plain: 'Each chunk is written to two indexes: a keyword index, so it can be found by its words, and a vector index, so it can be found by its meaning. A vector sums up the meaning of a chunk in numbers; texts with similar meanings end up close together.',
        tech: 'BGE-M3 turns each chunk into a 1024-dimensional vector (ONNX, in a separate model service); the vectors are written to Qdrant. For legislation the BM25 index keeps the first 5 letters of each word, to handle Turkish suffixes. Each index records the source version it was built from.',
        tags: ['BGE-M3', 'Qdrant', 'BM25', 'Embedding'],
      },
      {
        phase: 'question',
        title: 'Finds the relevant passages',
        en: 'Hybrid retrieval',
        plain: 'The question, with the chat history, first becomes a self-contained search query. Then it is searched both word by word and by meaning: someone who writes “I was let go” also finds the article about termination.',
        tech: 'Gemini writes the query and suggests up to 3 statute articles that govern the question. The query is turned into a vector with BGE-M3 too; BM25 and vector search run together and their results are merged with Reciprocal Rank Fusion (k=60).',
        tags: ['Query planning', 'BM25', 'BGE-M3', 'RRF'],
      },
      {
        phase: 'question',
        title: 'Chooses the most relevant',
        en: 'Reranking',
        plain: 'The 25 candidate passages found are scored one by one by a stronger model; the passages that best answer the question move to the top.',
        tech: 'Reranking with a cross-encoder; the model was converted to int8 ONNX and became 3.3 times faster. The articles named in planning join the candidates. The embedding and reranking models run in a separate model service that only the internal network can reach.',
        tags: ['bge-reranker-v2-m3', 'ONNX Runtime', 'Model service'],
      },
      {
        phase: 'question',
        title: 'Writes from the sources',
        en: 'Generation',
        plain: 'The language model sees only the chosen passages and writes the answer as short claims, each tied to its source.',
        tech: 'Structured output with a JSON schema, and context chosen within a token budget. On a transient error a fallback model takes over; source texts are marked as untrusted data (prompt-injection protection).',
        tags: ['Gemini', 'Structured output', 'Pydantic'],
      },
      {
        phase: 'question',
        title: 'Verifies every claim',
        en: 'Verification',
        plain: 'A separate model checks whether each claim is really in its source. An unsupported citation is removed, and a sentence left without support is marked “unverified”, so you can see which sentences to trust.',
        tech: 'Every claim–passage pair is classified as supported, partial or unsupported. The citation integrity check removes source ids a sentence may not cite.',
        tags: ['Claim verification', 'unverified'],
      },
    ],
    journeyTitle: 'The parts of the system: the journey of a request',
    journeyNote: 'An answer can take 1–2 minutes, so the work runs in the background',
    journey: [
      { where: 'Browser · Next.js', title: 'The question is sent', body: 'The interface passes the question to the API and shows live which step the work is at.', tech: 'React 19 · Tailwind 4' },
      { where: 'API · FastAPI', title: 'The request is accepted', body: 'The user is authenticated, the question is queued, and a “queued” reply goes back at once.', tech: '202 Accepted · Idempotency-Key' },
      { where: 'Job queue · PostgreSQL', title: 'The job waits its turn', body: 'The same question is never processed twice. If something fails, the job is retried automatically.', tech: 'up to 2 attempts · stuck-job recovery' },
      { where: 'Worker', title: 'The answer is produced', body: 'Search, writing and verification run in the background; the work continues even if the user closes the page.', tech: 'Qdrant · model service · Gemini' },
      { where: 'Database', title: 'The result is saved', body: 'The answer, its citations and the source versions used are stored together, so what an answer rested on can be traced later.', tech: 'corpus_version · index_version' },
    ],
    infrastructure: 'INFRASTRUCTURE',
    infraVm: 'A1 (ARM) · systemd services',
    infraPrivate: 'Qdrant and the model service only on the internal network',
    decisionsTitle: 'Engineering decisions',
    decisionsNote: '11 ADRs in the repository, each with its measurements',
    adrs: [
      { id: 'ADR 0001', title: 'Modular monolith', body: 'For a single developer, the overhead of microservices was not worth it. The app ships as one unit, but search, ingestion and the API are separate packages that can be split out when needed.' },
      { id: 'ADR 0002', title: 'A boundary between shared and private data', body: 'Users’ files and the shared legal sources sit behind separate storage and vector boundaries. A client document cannot leak into someone else’s answer, by design.' },
      { id: 'ADR 0005', title: 'int8 ONNX reranking', body: 'The reranking model was converted to int8 ONNX. On 40 questions reranking became 3.3 times faster, and the rate of finding the expected article did not change.' },
      { id: 'ADR 0006', title: 'Currency checks', body: 'Statute passages carry their official amendment notes. A provision that changed after the events, and a Yargıtay decision whose articles changed later, are flagged in the answer.' },
      { id: 'ADR 0009', title: 'Deadlines computed in code', body: 'The critical deadlines in a case analysis are computed by code, not by the model; the dates are read from the file and the deadline rules of the Civil Procedure Code (HMK) are applied.' },
      { id: 'ADR 0010 · 0011', title: 'Improving by measuring', body: 'Turkish stemming and the planner’s article hints raised the rate of finding the expected article in the top 25 from 92% to 97% on 72 questions. Options that did not pay off are on record too.' },
    ],
    glossaryTitle: 'A short glossary',
    glossaryNote: 'For non-technical readers',
    glossary: [
      ['RAG', 'Retrieval-Augmented Generation: the model finds the relevant documents before it writes, and relies on them.'],
      ['Hallucination', 'When a language model confidently produces information that is not true.'],
      ['Embedding', 'A representation that turns the meaning of a text into numbers. Texts with similar meanings end up close together.'],
      ['Vector database', 'A database that quickly finds the closest of these numeric representations. Here, Qdrant.'],
      ['Reranker', 'A more precise model that reads the candidates found together with the question and scores them again.'],
    ],
  },
  pipelineAnimation: {
    label: 'Steps of the answer pipeline',
    steps: [
      { title: 'Gathers the sources', en: 'Ingestion', caption: 'manifest → sha256 check → versioned store' },
      { title: 'Splits the text into chunks', en: 'Chunking', caption: 'article / paragraph / item structure kept' },
      { title: 'Indexes them', en: 'Embedding & indexing', caption: 'BGE-M3 → 1024-dimensional vector → Qdrant · BM25' },
      { title: 'Finds the relevant passages', en: 'Hybrid retrieval', caption: 'query planning → BM25 + BGE-M3 → RRF (k=60)' },
      { title: 'Chooses the most relevant', en: 'Reranking', caption: 'bge-reranker-v2-m3 · cross-encoder' },
      { title: 'Writes from the sources', en: 'Generation', caption: 'Gemini · structured output with a JSON schema' },
      { title: 'Verifies every claim', en: 'Verification', caption: 'supported · partial · unsupported' },
    ],
    stepOf: (step: number, total: number, preparation: boolean) =>
      `Step ${step} / ${total} · ${preparation ? 'preparation' : 'every question'}`,
    stepLabel: (step: number, title: string) => `Step ${step}: ${title}`,
    paused: 'Paused',
    current: (title: string, paused: boolean) => `${title}, ${paused ? 'paused. Click to resume.' : 'playing. Click to pause.'}`,
    goTo: (title: string) => `Go to the step: ${title}`,
    ingest: {
      docs: [
        { pill: 'Legislation', title: 'Labour Law No. 4857', meta: 'law · 122 articles' },
        { pill: 'Case law', title: 'Yargıtay 9th Civil Chamber', meta: 'decision · labour law' },
        { pill: 'Doctrine', title: 'Labour law course note (2026)', meta: 'course note · used with permission' },
      ],
      store: 'VERSIONED SOURCE STORE',
      documents: '/ 3 documents',
      immutable: '✓ Raw copy stored, never to be changed',
    },
    chunk: {
      heading: 'Labour Law No. 4857',
      article: 'Article 17 · Termination with notice',
      note: '4 chunks · each carries its citation, article path and page',
    },
    index: {
      chunks: 'Chunks',
      chunkSource: '4857 · Article 17',
      vectors: 'Vector index · Qdrant',
      vectorMeta: 'BGE-M3 · 1024 dims',
      keywords: 'Keyword index · BM25',
      keywordMeta: 'art. 17/4 · first 5 letters',
      note: 'When a question arrives, the same model turns it into a vector too; the search runs on both indexes.',
    },
    search: {
      keyword: 'Keyword · BM25',
      meaning: 'Meaning · BGE-M3',
      fused: 'Fused ranking · RRF',
      note: 'RRF score = Σ 1 / (60 + rank) · a passage ranked high in both lists comes first',
    },
    rerank: {
      top: 'Top 5 of 25 candidates',
      crossScore: 'cross-encoder score',
      rrfScore: 'RRF score',
      picked: 'Into the context',
    },
    write: {
      context: 'Context given to the model',
      budget: 'Context budget · 96k-token target',
    },
    verify: {
      supported: '✓ Supports',
      partial: '◐ Partly',
      unsupported: '✕ Does not support',
      verified: 'Verified',
      summary:
        '3 citations verified. The unsupported citation was removed, and the 1 claim left without support was marked “unverified”; the answer tells the user not to rely on it.',
    },
  },
  coverage: {
    label: 'COVERAGE',
    title: 'Labour law, for now.',
    lead: 'The search infrastructure is built per area of law. The source pool is versioned, and every answer records the version it was produced from.',
    groups: [
      { title: 'Legislation', tone: 'bg-accent', items: ['25 laws and 21 regulations', 'The Labour Law and the severance pay rules', 'The Labour Courts Law', 'The Turkish Code of Obligations', 'The Code of Civil Procedure', 'The Social Insurance Law'] },
      { title: 'Case law', tone: 'bg-fg2', items: ['49 Yargıtay decisions', 'Labour law disputes', 'Checked for whether the articles they rely on are still current'] },
      { title: 'Doctrine', tone: 'bg-doc', items: ['A labour law course note, used with permission', 'In a channel separate from the primary sources', 'Searched for every question'] },
    ],
  },
  security: {
    label: 'SECURITY AND DATA',
    title: 'Your files stay yours.',
    items: [
      { icon: 'key', title: 'Sign in with Google', body: 'Authentication runs on Supabase Auth; the token signature of every request is verified on the server.' },
      { icon: 'box', title: 'Workspace isolation', body: 'Every private record belongs to a workspace; queries cannot reach past that boundary.' },
      { icon: 'shield', title: 'Kept out of the shared pool', body: 'Files uploaded to cases are never written to the shared source index.' },
      { icon: 'lock', title: 'Verified connections', body: 'Database connections use TLS with full certificate verification.' },
      { icon: 'pin', title: 'Pinned dependencies', body: 'Packages are locked by hash; security scans run on every change and again every week.' },
      { icon: 'eyeOff', title: 'Logs that do not leak', body: 'Private file paths and request URLs are never written to the application logs.' },
    ],
  },
  demo: {
    badge: 'Demo project',
    title: 'A portfolio project, on real infrastructure.',
    body: 'BekenAI is a demo project on source-grounded legal AI. Its search, answer and verification pipeline runs on real Turkish labour law sources; but it is not a commercial product and does not give legal advice.',
    role: 'Design and development',
    github: 'View it on GitHub',
    sample: 'Sample case file',
    sampleNote: ' · a fictional reinstatement case file (in Turkish); attach it to a chat in the app and ask questions',
    limitsTitle: 'Known limits',
    limits: [
      'Only labour law is covered; other areas are not there yet.',
      'Because of the verification steps, an answer can take 1–2 minutes.',
      'The infrastructure is sized for a single-user demo.',
      'Scanned (image) PDFs cannot be read; a PDF with a text layer, a Word (DOCX) or a TXT file is needed.',
      'Answers are for research; they are not legal advice.',
    ],
  },
  faq: {
    label: 'FAQ',
    title: 'Frequently asked',
    items: [
      { q: 'Is this a real product?', a: 'No. BekenAI is a demo and portfolio project. Its search and verification pipeline works on real sources, but no commercial service is offered.' },
      { q: 'Which sources does it use?', a: 'Labour law legislation, Yargıtay decisions, doctrine used with permission, and the files you upload. Every answer shows the sources it used and their versions.' },
      {
        q: 'Can I upload my own file?',
        a: 'Yes. You can add a PDF, Word (DOCX) or TXT file to a chat or a case. Once the file is processed, questions are answered with page citations to its passages; what the file says is shown in a section separate from legislation and case law. Files are kept only in your workspace. If you have no file at hand, you can use the fictional sample case file in the demo section.',
      },
      {
        q: 'What are deep research and case analysis?',
        a: 'Deep research splits the question into up to 5 sub-questions, searches each one separately, fills the gaps in a second round and also fetches the articles the decisions found rely on; the result is a report with headings. Case analysis reads every file of a case, lists the legal issues, compares each with legislation, case law and doctrine, and computes the critical deadlines.',
      },
      { q: 'What if it cannot find an answer?', a: 'If no relevant source is found, BekenAI does not guess; it says so plainly and, if you wish, searches the web in a separate, labelled section of the answer. Sentences that cannot be verified against a source are marked in the answer as well.' },
      { q: 'Why can an answer take a few minutes?', a: 'Every claim goes through a separate verification step. While you wait, you can see which step the work is at.' },
      { q: 'Can I ask in English?', a: 'Not yet. The interface is available in English, but the sources are Turkish and BekenAI searches and answers in Turkish, so questions need to be asked in Turkish.' },
    ],
  },
  cta: {
    title: 'Try answers you can trace to a source.',
    body: 'Sign in with your Google account and ask a labour law question in Turkish. This is a demo environment; answers are for research.',
  },
  footer: {
    copyright: '© 2026 · Demo project',
    disclaimer: 'Not a substitute for legal advice.',
  },
};
